/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/boxer.glb -o src/components/Boxer.jsx -k -K -r public 
Author: SmugglersStudio (https://sketchfab.com/SmugglersStudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/frog-peasant-b06af7ff11eb485bbbcb248d2f5427f5
Title: Frog Peasant
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Boxer({
  animation,
  ...props
}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/boxer.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.283}>
          <group name="frog-peasantfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="root" position={[-9.44, -26.253, 13.492]} rotation={[-1.521, -0.131, -0.875]}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_29" position={[-9.44, -26.253, 13.492]} rotation={[-1.521, -0.131, -0.875]} />
                    <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['frog-peasant']} skeleton={nodes.Object_30.skeleton} />
                  </group>
                </group>
                <group name="retop" position={[-9.44, -26.253, 13.492]} rotation={[-1.521, -0.131, -0.875]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/boxer.glb')
